<?php

use Illuminate\Database\Seeder;

class CantonsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = \Carbon\Carbon::now();

        $cantons = [
            ["code"=>"01","name"=>"CUENCA","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"GIRÓN","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"GUALACEO","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"NABÓN","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"PAUTE","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"PUCARA","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"SAN FERNANDO","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"SANTA ISABEL","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"SIGSIG","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"10","name"=>"OÑA","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"11","name"=>"CHORDELEG","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"12","name"=>"EL PAN","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"13","name"=>"SEVILLA DE ORO","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"14","name"=>"GUACHAPALA","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"15","name"=>"CAMILO PONCE ENRÍQUEZ","province_code"=>"01","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"GUARANDA","province_code"=>"02","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"CHILLANES","province_code"=>"02","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"CHIMBO","province_code"=>"02","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"ECHEANDÍA","province_code"=>"02","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"SAN MIGUEL","province_code"=>"02","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"CALUMA","province_code"=>"02","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"LAS NAVES","province_code"=>"02","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"AZOGUES","province_code"=>"03","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"BIBLIÁN","province_code"=>"03","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"CAÑAR","province_code"=>"03","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"LA TRONCAL","province_code"=>"03","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"EL TAMBO","province_code"=>"03","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"DÉLEG","province_code"=>"03","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"SUSCAL","province_code"=>"03","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"TULCÁN","province_code"=>"04","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"BOLÍVAR","province_code"=>"04","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"ESPEJO","province_code"=>"04","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"MIRA","province_code"=>"04","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"MONTÚFAR","province_code"=>"04","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"SAN PEDRO DE HUACA","province_code"=>"04","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"LATACUNGA","province_code"=>"05","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"LA MANÁ","province_code"=>"05","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"PANGUA","province_code"=>"05","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"PUJILI","province_code"=>"05","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"SALCEDO","province_code"=>"05","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"SAQUISILÍ","province_code"=>"05","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"SIGCHOS","province_code"=>"05","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"RIOBAMBA","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"ALAUSI","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"COLTA","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"CHAMBO","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"CHUNCHI","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"GUAMOTE","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"GUANO","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"PALLATANGA","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"PENIPE","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"10","name"=>"CUMANDÁ","province_code"=>"06","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"MACHALA","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"ARENILLAS","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"ATAHUALPA","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"BALSAS","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"CHILLA","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"EL GUABO","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"HUAQUILLAS","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"MARCABELÍ","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"PASAJE","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"10","name"=>"PIÑAS","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"11","name"=>"PORTOVELO","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"12","name"=>"SANTA ROSA","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"13","name"=>"ZARUMA","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"14","name"=>"LAS LAJAS","province_code"=>"07","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"ESMERALDAS","province_code"=>"08","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"ELOY ALFARO","province_code"=>"08","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"MUISNE","province_code"=>"08","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"QUININDÉ","province_code"=>"08","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"SAN LORENZO","province_code"=>"08","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"ATACAMES","province_code"=>"08","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"RIOVERDE","province_code"=>"08","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"LA CONCORDIA","province_code"=>"08","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"GUAYAQUIL","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"ALFREDO BAQUERIZO MORENO (JUJÁN)","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"BALAO","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"BALZAR","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"COLIMES","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"DAULE","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"DURÁN","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"EL EMPALME","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"EL TRIUNFO","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"10","name"=>"MILAGRO","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"11","name"=>"NARANJAL","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"12","name"=>"NARANJITO","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"13","name"=>"PALESTINA","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"14","name"=>"PEDRO CARBO","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"16","name"=>"SAMBORONDÓN","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"18","name"=>"SANTA LUCÍA","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"19","name"=>"SALITRE (URBINA JADO)","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"20","name"=>"SAN JACINTO DE YAGUACHI","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"21","name"=>"PLAYAS","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"22","name"=>"SIMÓN BOLÍVAR","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"23","name"=>"CORONEL MARCELINO MARIDUEÑA","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"24","name"=>"LOMAS DE SARGENTILLO","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"25","name"=>"NOBOL","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"27","name"=>"GENERAL ANTONIO ELIZALDE","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"28","name"=>"ISIDRO AYORA","province_code"=>"09","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"IBARRA","province_code"=>"10","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"ANTONIO ANTE","province_code"=>"10","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"COTACACHI","province_code"=>"10","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"OTAVALO","province_code"=>"10","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"PIMAMPIRO","province_code"=>"10","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"SAN MIGUEL DE URCUQUÍ","province_code"=>"10","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"LOJA","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"CALVAS","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"CATAMAYO","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"CELICA","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"CHAGUARPAMBA","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"ESPÍNDOLA","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"GONZANAMÁ","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"MACARÁ","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"PALTAS","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"10","name"=>"PUYANGO","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"11","name"=>"SARAGURO","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"12","name"=>"SOZORANGA","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"13","name"=>"ZAPOTILLO","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"14","name"=>"PINDAL","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"15","name"=>"QUILANGA","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"16","name"=>"OLMEDO","province_code"=>"11","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"BABAHOYO","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"BABA","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"MONTALVO","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"PUEBLOVIEJO","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"QUEVEDO","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"URDANETA","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"VENTANAS","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"VÍNCES","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"PALENQUE","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"10","name"=>"BUENA FÉ","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"11","name"=>"VALENCIA","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"12","name"=>"MOCACHE","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"13","name"=>"QUINSALOMA","province_code"=>"12","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"PORTOVIEJO","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"BOLÍVAR","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"CHONE","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"EL CARMEN","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"FLAVIO ALFARO","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"JIPIJAPA","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"JUNÍN","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"MANTA","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"MONTECRISTI","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"10","name"=>"PAJÁN","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"11","name"=>"PICHINCHA","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"12","name"=>"ROCAFUERTE","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"13","name"=>"SANTA ANA","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"14","name"=>"SUCRE","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"15","name"=>"TOSAGUA","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"16","name"=>"24 DE MAYO","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"17","name"=>"PEDERNALES","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"18","name"=>"OLMEDO","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"19","name"=>"PUERTO LÓPEZ","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"20","name"=>"JAMA","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"21","name"=>"JARAMIJÓ","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"22","name"=>"SAN VICENTE","province_code"=>"13","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"MORONA","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"GUALAQUIZA","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"LIMÓN INDANZA","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"PALORA","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"SANTIAGO","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"SUCÚA","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"HUAMBOYA","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"SAN JUAN BOSCO","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"TAISHA","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"10","name"=>"LOGROÑO","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"11","name"=>"PABLO SEXTO","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"12","name"=>"TIWINTZA","province_code"=>"14","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"TENA","province_code"=>"15","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"ARCHIDONA","province_code"=>"15","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"EL CHACO","province_code"=>"15","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"QUIJOS","province_code"=>"15","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"CARLOS JULIO AROSEMENA TOLA","province_code"=>"15","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"PASTAZA","province_code"=>"16","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"MERA","province_code"=>"16","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"SANTA CLARA","province_code"=>"16","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"ARAJUNO","province_code"=>"16","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"QUITO","province_code"=>"17","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"CAYAMBE","province_code"=>"17","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"MEJIA","province_code"=>"17","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"PEDRO MONCAYO","province_code"=>"17","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"RUMIÑAHUI","province_code"=>"17","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"SAN MIGUEL DE LOS BANCOS","province_code"=>"17","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"PEDRO VICENTE MALDONADO","province_code"=>"17","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"PUERTO QUITO","province_code"=>"17","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"AMBATO","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"BAÑOS DE AGUA SANTA","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"CEVALLOS","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"MOCHA","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"PATATE","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"QUERO","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"SAN PEDRO DE PELILEO","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"SANTIAGO DE PÍLLARO","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"TISALEO","province_code"=>"18","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"ZAMORA","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"CHINCHIPE","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"NANGARITZA","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"YACUAMBI","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"YANTZAZA (YANZATZA)","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"EL PANGUI","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"CENTINELA DEL CÓNDOR","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"08","name"=>"PALANDA","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"09","name"=>"PAQUISHA","province_code"=>"19","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"SAN CRISTÓBAL","province_code"=>"20","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"ISABELA","province_code"=>"20","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"SANTA CRUZ","province_code"=>"20","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"LAGO AGRIO","province_code"=>"21","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"GONZALO PIZARRO","province_code"=>"21","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"PUTUMAYO","province_code"=>"21","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"SHUSHUFINDI","province_code"=>"21","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"05","name"=>"SUCUMBÍOS","province_code"=>"21","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"06","name"=>"CASCALES","province_code"=>"21","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"07","name"=>"CUYABENO","province_code"=>"21","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"ORELLANA","province_code"=>"22","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"AGUARICO","province_code"=>"22","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"LA JOYA DE LOS SACHAS","province_code"=>"22","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"LORETO","province_code"=>"22","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"SANTO DOMINGO","province_code"=>"23","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"SANTA ELENA","province_code"=>"24","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"02","name"=>"LA LIBERTAD","province_code"=>"24","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"SALINAS","province_code"=>"24","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"01","name"=>"LAS GOLONDRINAS","province_code"=>"90","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"03","name"=>"MANGA DEL CURA","province_code"=>"90","created_at"=>$date,"updated_at"=>$date],
            ["code"=>"04","name"=>"EL PIEDRERO","province_code"=>"90","created_at"=>$date,"updated_at"=>$date],
        ];

        DB::table('cantons')->insert($cantons);
    }
}
